@startuml
'https://plantuml.com/sequence-diagram

autonumber

title Test framework main process

actor Runner
participant IRunIntegrationTests
participant ProjectTestRunner
participant TestTool
database OutputDirectory
actor User

Runner -> IRunIntegrationTests : IntegrationTests(Test tool name,Version)
IRunIntegrationTests -> IRunIntegrationTests : UpdateTestTool
IRunIntegrationTests -> IRunIntegrationTests : Test projects collect

loop#Gold Test projects iteration
    IRunIntegrationTests -> ProjectTestRunner : RunTests(Test project,Test tool name,Version)
    
    ProjectTestRunner -> OutputDirectory ++ #Grey : Create output directory
    ProjectTestRunner -> OutputDirectory : Build test project to the output directory
    
    ProjectTestRunner->TestTool ++ #Grey : Start(Test assembly path, xml result path, version)
    TestTool -> OutputDirectory : XML test result file
    TestTool --> ProjectTestRunner -- : Exit
    
    ProjectTestRunner -> OutputDirectory : Convert XML->HTML test result file
    
    ProjectTestRunner -> ProjectTestRunner : Check test result
    
    alt#Gold All tests pass
        ProjectTestRunner --> IRunIntegrationTests : RunTests return     
     else #Pink Any test failed
     autonumber stop
        IRunIntegrationTests x<-- ProjectTestRunner : throw Exception
    end alt

end loop

alt#Gold no exception
    autonumber resume
    IRunIntegrationTests --> Runner : IntegrationTests success output
else #Pink exception
    autonumber stop
    Runner -->x IRunIntegrationTests : IntegrationTests fail output
end alt

autonumber stop

== Few moments later ==

User --> OutputDirectory : User can read\nlast test artifacts

@enduml